SELECT SUM(SHOURS),PNAME FROM SERV
LEFT JOIN Person
ON SERV.SSN = Person.SSN
LEFT JOIN OWN
ON SERV.REGNO = OWN.PLANE_REG
INNER JOIN Corporation
ON OWN.SSN = Corporation.SSN
GROUP BY PNAME
ORDER BY SUM(SHOURS) DESC;
